[alum."gazebosim/ros_gz"]
branch = "jazzy"
[alum."gazebo-release/gz_cmake_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_common_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_dartsim_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_fuel_tools_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_gui_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_math_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_msgs_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_ogre_next_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_physics_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_plugin_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_rendering_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_sensors_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_sim_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_tools_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_transport_vendor"]
branch = "jazzy"
[alum."gazebo-release/gz_utils_vendor"]
branch = "jazzy"
[alum."gazebo-release/sdformat_vendor"]
branch = "jazzy"
[alum."pal-robotics/kangaroo_moveit_config"]
[alum."pal-robotics/kangaroo_simulation"]
[alum."pal-robotics/realsense_gazebo_plugin"]
[alum."pal-robotics/realsense_simulation"]
[alum."ros/sdformat_urdf"]
branch = "jazzy"
[alum."ros-controls/control_msgs"]
branch = "jazzy"
[alum."ros-controls/control_toolbox"]
branch = "jazzy"
packages = {"control_toolbox" = {do_check = false}}
[alum."ros-controls/kinematics_interface"]
branch = "jazzy"
[alum."ros-controls/realtime_tools"]
branch = "jazzy"
packages = {"realtime_tools" = {do_check = false}}
[alum."ros-controls/ros2_control"]
branch = "jazzy"
[alum."ros-controls/ros2_control".packages]
controller_interface = {do_check = false}
controller_manager = {do_check = false}
joint_limits = {do_check = false}
hardware_interface = {do_check = false}
hardware_interface_testing = {do_check = false}
transmission_interface = {do_check = false}
[alum."ros-controls/ros2_controllers"]
branch = "jazzy"
[alum."ros-controls/ros2_controllers".packages]
ackermann_steering_controller = {do_check = false}
admittance_controller = {do_check = false}
bicycle_steering_controller = {do_check = false}
chained_filter_controller = {do_check = false}
diff_drive_controller = {do_check = false}
effort_controllers = {do_check = false}
force_torque_sensor_broadcaster = {do_check = false}
forward_command_controller = {do_check = false}
gps_sensor_broadcaster = {do_check = false}
gripper_controllers = {do_check = false}
imu_sensor_broadcaster = {do_check = false}
joint_state_broadcaster = {do_check = false}
joint_trajectory_controller = {do_check = false}
magnetometer_broadcaster = {do_check = false}
motion_primitives_controllers = {do_check = false}
mecanum_drive_controller = {do_check = false}
omni_wheel_drive_controller = {do_check = false}
parallel_gripper_controller = {do_check = false}
pid_controller = {do_check = false}
pose_broadcaster = {do_check = false}
position_controllers = {do_check = false}
range_sensor_broadcaster = {do_check = false}
state_interfaces_broadcaster = {do_check = false}
tricycle_controller = {do_check = false}
tricycle_steering_controller = {do_check = false}
velocity_controllers = {do_check = false}

[humble."clementPene/pal_atc".packages]
pal_atc_controller_configuration = {do_check = false}
pal_atc_description = {do_check = false}
pal_atc_bringup = {do_check = false}
[humble."gepetto/Quest-Teleoperation-Panda"]
native = ["v4l-utils"]
propagated = ["python3Packages.pyarrow"]
[humble."agimus-project/agimus-controller"]
branch = "main"
[humble."agimus-project/agimus-demos"]
branch = "main"
[humble."agimus-project/agimus-franka-description"]
branch = "main"
[humble."agimus-project/agimus-franka-ros2"]
branch = "main"
[humble."agimus-project/agimus-libfranka"]
branch = "main"
do_check = false
[humble."agimus-project/agimus-libfranka-common"]
[humble."agimus-project/agimus-msgs"]
[humble."agimus-project/agimus_pytroller"]

[humble."gbartyzel/ros2_net_ft_driver"]
branch = "humble"
packages = {"net_ft_driver" = {native = ["pkg-config"], propagated = ["curl", "curlpp"]}}

[humble."jpgtzg/omni_drive_controller".packages]
omni_drive_controller = {do_check = false}

[jazzy."agimus-project/agimus-controller"]
branch = "main"
[jazzy."agimus-project/agimus-demos"]
branch = "main"
[jazzy."agimus-project/agimus-franka-description"]
branch = "main"
[jazzy."agimus-project/agimus-franka-ros2"]
branch = "main"
[jazzy."agimus-project/agimus-libfranka"]
branch = "main"
do_check = false
[jazzy."agimus-project/agimus-libfranka-common"]
[jazzy."agimus-project/agimus-msgs"]
[jazzy."agimus-project/agimus_pytroller"]

[jazzy."gbartyzel/ros2_net_ft_driver"]
packages = {"net_ft_driver" = {check = ["ament-lint-auto"], native = ["pkg-config"], propagated = ["curl", "curlpp"]}}

[jazzy."pal-robotics/kangaroo_moveit_config"]
[jazzy."pal-robotics/kangaroo_robot".packages]
kangaroo_bringup = {do_check = false}
kangaroo_controller_configuration = {do_check = false}
kangaroo_description = {do_check = false}
[jazzy."pal-robotics/kangaroo_simulation"]
[jazzy."pal-robotics/realsense_simulation"]
do_check = false

[jazzy."ros-controls/ros2_control_demos"]
branch = "jazzy"
[jazzy."ros-controls/ros2_control_demos".packages.example_1]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_2]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_3]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_4]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_5]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_6]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_7]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_8]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_9]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_10]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_11]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_12]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_13]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_14]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_15]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_16]
do_check = false
[jazzy."ros-controls/ros2_control_demos".packages.example_17]
do_check = false

[jazzy."stack-of-tasks/odri_dual_motor_testbed_robot"]
[jazzy."stack-of-tasks/odri_forward_command_controller"]
[jazzy."stack-of-tasks/odri_gz_ros2_control"]

[jazzy."Tiago-Pro-Harmonic/br2_gazebo_worlds"]
do_check = false
[jazzy."Tiago-Pro-Harmonic/gep_tiago_pro_control_stack"]
[jazzy."Tiago-Pro-Harmonic/launch_pal"]
[jazzy."Tiago-Pro-Harmonic/omni_base_robot".packages]
omni_base_bringup = {do_check = false}
omni_base_description = {do_check = false}
omni_base_controller_configuration = {do_check = false}
[jazzy."Tiago-Pro-Harmonic/pal_pro_gripper".packages]
pal_pro_gripper_bringup = {do_check = false}
pal_pro_gripper_description = {do_check = false}
pal_pro_gripper_controller_configuration = {do_check = false}
[jazzy."Tiago-Pro-Harmonic/pal_sea_arm".packages]
pal_sea_arm_bringup = {do_check = false}
pal_sea_arm_description = {do_check = false}
pal_sea_arm_controller_configuration = {do_check = false}
[jazzy."Tiago-Pro-Harmonic/pal_sea_arm_moveit_config"]
do_check = false
[jazzy."Tiago-Pro-Harmonic/pal_urdf_utils"]
do_check = false
[jazzy."Tiago-Pro-Harmonic/play_motion2"]
do_check = false
[jazzy."Tiago-Pro-Harmonic/tiago_pro_head_robot".packages]
tiago_pro_head_bringup = {do_check = false}
tiago_pro_head_description = {do_check = false}
tiago_pro_head_controller_configuration = {do_check = false}
[jazzy."Tiago-Pro-Harmonic/tiago_pro_moveit_config"]
do_check = false
[jazzy."Tiago-Pro-Harmonic/tiago_pro_robot".packages]
tiago_pro_bringup = {do_check = false}
tiago_pro_description = {do_check = false}
tiago_pro_controller_configuration = {do_check = false}
[jazzy."Tiago-Pro-Harmonic/tiago_pro_simulation".packages]
tiago_pro_gazebo = {do_check = false}

[kilted."agimus-project/agimus-controller"]
branch = "main"
[kilted."agimus-project/agimus-demos"]
branch = "main"
[kilted."agimus-project/agimus-franka-description"]
branch = "main"
[kilted."agimus-project/agimus-franka-ros2"]
branch = "main"
[kilted."agimus-project/agimus-libfranka"]
branch = "main"
do_check = false
[kilted."agimus-project/agimus-libfranka-common"]
[kilted."agimus-project/agimus-msgs"]

[lyrical."agimus-project/agimus-controller"]
branch = "main"
[lyrical."agimus-project/agimus-demos"]
branch = "main"
[lyrical."agimus-project/agimus-franka-description"]
branch = "main"
[lyrical."agimus-project/agimus-franka-ros2"]
branch = "main"
[lyrical."agimus-project/agimus-libfranka"]
branch = "main"
do_check = false
[lyrical."agimus-project/agimus-libfranka-common"]
[lyrical."agimus-project/agimus-msgs"]

[rolling."agimus-project/agimus-controller"]
branch = "main"
[rolling."agimus-project/agimus-demos"]
branch = "main"
[rolling."agimus-project/agimus-franka-description"]
branch = "main"
[rolling."agimus-project/agimus-franka-ros2"]
branch = "main"
[rolling."agimus-project/agimus-libfranka"]
branch = "main"
do_check = false
[rolling."agimus-project/agimus-libfranka-common"]
[rolling."agimus-project/agimus-msgs"]
